services:
  - type: web
    name: dynamic-tune
    env: python
    plan: free
    region: oregon
    runtime: python
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 60 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
