services:
  - type: web
    name: dynamic-tune
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 60
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
